# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.2.0-stretch-browsers

set_env: &set_env
  name: Setup Environment Variables
  command: |
    echo 'export CIRCLE_PR_NUMBER="${CIRCLE_PR_NUMBER:-${CIRCLE_PULL_REQUEST##*/}}"' >> $BASH_ENV
    echo "export CIRCLE_PR_BASE_SHA=`curl -s https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pulls/${CIRCLE_PR_NUMBER} | jq -r '.base.ref'`" >> $BASH_ENV
    echo 'export AFFECTED_ARGS="--base ${CIRCLE_PR_BASE_SHA} --parallel"' >> $BASH_ENV
    cat $BASH_ENV
    source $BASH_ENV
    echo $CIRCLE_PR_NUMBER
    echo $CIRCLE_PR_BASE_SHA
    echo $AFFECTED_ARGS
yarn_cache: &yarn_cache
  keys:
    - yarn-dependencies-12.2.0-{{ checksum "yarn.lock" }}
    - yarn-dependencies-12.2.0-
    # fallback to using the latest cache if no exact match is found
    - yarn-dependencies-12.2.0-

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run:
          <<: *set_env
      - run: echo $CIRCLE_PR_BRANCH
      - restore_cache:
          <<: *yarn_cache
      - run: yarn install --frozen-lockfile --non-interactive
      - save_cache:
          key: yarn-dependencies-12.2.0-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  format-check:
    <<: *defaults
    steps:
      - checkout
      - run:
          <<: *set_env
      - restore_cache:
          <<: *yarn_cache
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn format:check ${AFFECTED_ARGS}

workflows:
  version: 2
  pr_check:
    jobs:
      - install
      - format-check:
          requires:
            - install
